-- Fix: Change id columns from BIGINT GENERATED BY DEFAULT AS IDENTITY to SERIAL
-- Run this in Supabase SQL Editor to fix auto-increment

-- Drop existing tables (data will be lost - this is fresh setup)
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS ca_master CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS vouchers CASCADE;
DROP TABLE IF EXISTS trial_balance CASCADE;

-- Recreate with SERIAL (auto-increment)
CREATE TABLE clients (
    id SERIAL PRIMARY KEY,
    constitution TEXT,
    name TEXT NOT NULL,
    address TEXT,
    pincode TEXT,
    city TEXT,
    district TEXT,
    state TEXT,
    country TEXT DEFAULT 'India',
    phone TEXT,
    email TEXT,
    registrations JSONB DEFAULT '{}',
    contactPersons JSONB DEFAULT '[]',
    documents JSONB DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ca_master (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    pincode TEXT,
    city TEXT,
    district TEXT,
    state TEXT,
    country TEXT DEFAULT 'India',
    phone TEXT,
    email TEXT,
    panNumber TEXT,
    gstin TEXT,
    membershipNumber TEXT,
    firmName TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
    id SERIAL PRIMARY KEY,
    client_id BIGINT,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    category TEXT,
    opening_balance NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vouchers (
    id SERIAL PRIMARY KEY,
    client_id BIGINT,
    voucher_type TEXT NOT NULL,
    voucher_number TEXT,
    voucher_date DATE NOT NULL,
    amount NUMERIC NOT NULL,
    account_id BIGINT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE trial_balance (
    id SERIAL PRIMARY KEY,
    client_id BIGINT,
    financial_year TEXT NOT NULL,
    as_on_date DATE,
    account_name TEXT NOT NULL,
    debit NUMERIC DEFAULT 0,
    credit NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE ca_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE vouchers ENABLE ROW LEVEL SECURITY;
ALTER TABLE trial_balance ENABLE ROW LEVEL SECURITY;

-- Create policies
-- Clients
CREATE POLICY "Allow public read access to clients" ON clients FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert to clients" ON clients FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update to clients" ON clients FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete from clients" ON clients FOR DELETE TO anon, authenticated USING (true);

-- CA Master
CREATE POLICY "Allow public read access to ca_master" ON ca_master FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert to ca_master" ON ca_master FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update to ca_master" ON ca_master FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete from ca_master" ON ca_master FOR DELETE TO anon, authenticated USING (true);

-- Accounts
CREATE POLICY "Allow public read access to accounts" ON accounts FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert to accounts" ON accounts FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update to accounts" ON accounts FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete from accounts" ON accounts FOR DELETE TO anon, authenticated USING (true);

-- Vouchers
CREATE POLICY "Allow public read access to vouchers" ON vouchers FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert to vouchers" ON vouchers FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update to vouchers" ON vouchers FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete from vouchers" ON vouchers FOR DELETE TO anon, authenticated USING (true);

-- Trial Balance
CREATE POLICY "Allow public read access to trial_balance" ON trial_balance FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert to trial_balance" ON trial_balance FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update to trial_balance" ON trial_balance FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete from trial_balance" ON trial_balance FOR DELETE TO anon, authenticated USING (true);

SELECT 'Tables recreated with SERIAL IDs!' as status;
