-- TaxGlue Supabase: Create Tables & RLS Policies
-- Run this in Supabase SQL Editor

-- ============================================
-- CREATE TABLES
-- ============================================

-- CLIENTS TABLE
CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    constitution TEXT,
    name TEXT NOT NULL,
    address TEXT,
    pincode TEXT,
    city TEXT,
    district TEXT,
    state TEXT,
    country TEXT DEFAULT 'India',
    phone TEXT,
    email TEXT,
    registrations JSONB DEFAULT '{}',
    contactPersons JSONB DEFAULT '[]',
    documents JSONB DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- CA MASTER TABLE
CREATE TABLE IF NOT EXISTS ca_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    pincode TEXT,
    city TEXT,
    district TEXT,
    state TEXT,
    country TEXT DEFAULT 'India',
    phone TEXT,
    email TEXT,
    panNumber TEXT,
    gstin TEXT,
    membershipNumber TEXT,
    firmName TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ACCOUNTS TABLE (Chart of Accounts)
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    category TEXT,
    opening_balance NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- VOUCHERS TABLE
CREATE TABLE IF NOT EXISTS vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT,
    voucher_type TEXT NOT NULL,
    voucher_number TEXT,
    voucher_date DATE NOT NULL,
    amount NUMERIC NOT NULL,
    account_id BIGINT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- TRIAL BALANCE TABLE
CREATE TABLE IF NOT EXISTS trial_balance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT,
    financial_year TEXT NOT NULL,
    as_on_date DATE,
    account_name TEXT NOT NULL,
    debit NUMERIC DEFAULT 0,
    credit NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- ENABLE RLS
-- ============================================

ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE ca_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE vouchers ENABLE ROW LEVEL SECURITY;
ALTER TABLE trial_balance ENABLE ROW LEVEL SECURITY;

-- ============================================
-- RLS POLICIES FOR CLIENTS
-- ============================================

DROP POLICY IF EXISTS "Allow public read access to clients" ON clients;
DROP POLICY IF EXISTS "Allow public insert to clients" ON clients;
DROP POLICY IF EXISTS "Allow public update to clients" ON clients;
DROP POLICY IF EXISTS "Allow public delete from clients" ON clients;

CREATE POLICY "Allow public read access to clients" ON clients FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert to clients" ON clients FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update to clients" ON clients FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete from clients" ON clients FOR DELETE TO anon, authenticated USING (true);

-- ============================================
-- RLS POLICIES FOR CA_MASTER
-- ============================================

DROP POLICY IF EXISTS "Allow public read access to ca_master" ON ca_master;
DROP POLICY IF EXISTS "Allow public insert to ca_master" ON ca_master;
DROP POLICY IF EXISTS "Allow public update to ca_master" ON ca_master;
DROP POLICY IF EXISTS "Allow public delete from ca_master" ON ca_master;

CREATE POLICY "Allow public read access to ca_master" ON ca_master FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert to ca_master" ON ca_master FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update to ca_master" ON ca_master FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete from ca_master" ON ca_master FOR DELETE TO anon, authenticated USING (true);

-- ============================================
-- RLS POLICIES FOR ACCOUNTS
-- ============================================

DROP POLICY IF EXISTS "Allow public read access to accounts" ON accounts;
DROP POLICY IF EXISTS "Allow public insert to accounts" ON accounts;
DROP POLICY IF EXISTS "Allow public update to accounts" ON accounts;
DROP POLICY IF EXISTS "Allow public delete from accounts" ON accounts;

CREATE POLICY "Allow public read access to accounts" ON accounts FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert to accounts" ON accounts FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update to accounts" ON accounts FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete from accounts" ON accounts FOR DELETE TO anon, authenticated USING (true);

-- ============================================
-- RLS POLICIES FOR VOUCHERS
-- ============================================

DROP POLICY IF EXISTS "Allow public read access to vouchers" ON vouchers;
DROP POLICY IF EXISTS "Allow public insert to vouchers" ON vouchers;
DROP POLICY IF EXISTS "Allow public update to vouchers" ON vouchers;
DROP POLICY IF EXISTS "Allow public delete from vouchers" ON vouchers;

CREATE POLICY "Allow public read access to vouchers" ON vouchers FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert to vouchers" ON vouchers FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update to vouchers" ON vouchers FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete from vouchers" ON vouchers FOR DELETE TO anon, authenticated USING (true);

-- ============================================
-- RLS POLICIES FOR TRIAL_BALANCE
-- ============================================

DROP POLICY IF EXISTS "Allow public read access to trial_balance" ON trial_balance;
DROP POLICY IF EXISTS "Allow public insert to trial_balance" ON trial_balance;
DROP POLICY IF EXISTS "Allow public update to trial_balance" ON trial_balance;
DROP POLICY IF EXISTS "Allow public delete from trial_balance" ON trial_balance;

CREATE POLICY "Allow public read access to trial_balance" ON trial_balance FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert to trial_balance" ON trial_balance FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public update to trial_balance" ON trial_balance FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete from trial_balance" ON trial_balance FOR DELETE TO anon, authenticated USING (true);

-- ============================================
-- VERIFY SETUP
-- ============================================

SELECT 'Tables created and RLS enabled!' as status;
